### ISSUE TITLE
I get an error on some files

### ISSUE THREAD

**Issue by himo456** [nesrak1/AddressablesTools#6]
Error in some games like game 
Astalon Tears of the Earth

Example patchcrc catalog.json
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at AddressablesTools.Catalog.ContentCatalogData.Read(ContentCatalogDataJson data) in C:\Users\nesquack\Documents\GitRepos\AddressablesTools\AddressablesTools\Catalog\ContentCatalogData.cs:line 61
at AddressablesTools.AddressablesJsonParser.FromString(String data) in C:\Users\nesquack\Documents\GitRepos\AddressablesTools\AddressablesTools\AddressablesJsonParser.cs:line 23
   at Program.<<Main>$>g__PatchCrcExample|0_1(String[] args) in C:\Users\nesquack\Documents\GitRepos\AddressablesTools\Example\Program.cs:line 59
   at Program.<Main>$(String[] args) in C:\Users\nesquack\Documents\GitRepos\AddressablesTools\Example\Program.cs:line 103

**Comment by nesrak1** [comment]
Please try the latest prerelease to see if it solves your crash.

**Comment by veseliykavunteam** [comment]
hello. I was tried use this command example patchcrc catalog.json
and get the follow error. What it is ? May i did something wrong ? Thanks

Unhandled exception. System.FormatException: The input string '{UnityEngine.AddressableAssets.Addressables.RuntimePath}\StandaloneWindows64\build' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Int32.Parse(String s)
   at AddressablesTools.Catalog.ContentCatalogData.ReadResources(ContentCatalogDataJson data) in D:\a\AddressablesTools\AddressablesTools\AddressablesTools\Catalog\ContentCatalogData.cs:line 182
   at AddressablesTools.Catalog.ContentCatalogData.Read(ContentCatalogDataJson data) in D:\a\AddressablesTools\AddressablesTools\AddressablesTools\Catalog\ContentCatalogData.cs:line 90
   at AddressablesTools.AddressablesCatalogFileParser.FromJsonString(String data) in D:\a\AddressablesTools\AddressablesTools\AddressablesTools\AddressablesCatalogFileParser.cs:line 38
   at Program.<<Main>$>g__PatchCrcExample|0_3(String[] args) in D:\a\AddressablesTools\AddressablesTools\Example\Program.cs:line 160
   at Program.<Main>$(String[] args) in D:\a\AddressablesTools\AddressablesTools\Example\Program.cs:line 230
